# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

  pipelines:
  default:
    - step:
        name: Test
        script:
          - cd sample-python-app
          - pip install -r requirements.txt
          - ./manage.py test
          
    - step:
        name: Build
        script:
          - cd sample-python-app
          - git archive --format=tar.gz master -o sample-app.tar.gz
        artifacts:
          - sample-python-app/sample-app.tar.gz
      
    - step:
        name: Deploy to production
        deployment: production
        caches:
          - pip
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: $HEROKU_API_KEY
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              ZIP_FILE: sample-python-app/sample-app.tar.gz